version: '3.7'

services: 
  ts-node-docker:
    build:
      context: .
      dockerfile: dockerfile
      target: base
    volumes: 
      - ./src:/usr/src/app/src
    container_name: cambook-backend-server
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev