FROM node:14 as base

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

FROM base as test
RUN npm test

FROM base as production

ENV NODE_PATH ./dist

RUN npm test

RUN npm run build
